#!/bin/bash

export OPENSHIFT_MONGODB_DB_HOST=ds021671.mlab.com
export OPENSHIFT_MONGODB_DB_PORT=21671
export OPENSHIFT_APP_NAME=girlsday
export OPENSHIFT_MONGODB_DB_USERNAME=u
export OPENSHIFT_MONGODB_DB_PASSWORD=p
